### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Shashwat-srivastav**

### CODE REVIEW

**Comment by TheAdityaGupta** [comment]
This will count as just one pr and you will have to make 3 more valid pr to be eligible for swags.
you can revert changes if you wish to make diff pr for each file or comment to inform if you want to get it merged as it is.

**Comment by Shashwat-srivastav** [comment]
merge as it is as these are different files.

**Comment by Shashwat-srivastav** [comment]
my 4 PRs are merged.

**Comment by TheAdityaGupta** [comment]
Can you give link to those repos because the ones where mine were accepted got excluded from the event

**Comment by Shashwat-srivastav** [comment]
ok
https://github.com/arpit456jain/Beginner-Friendly-Repos-for-Hacktoberfest
https://github.com/DiyaVj/Profile-Card-Collection
and yours

**Comment by Shashwat-srivastav** [comment]
2 in profile card and 1 in beginner friendly and yours

**Pull request merged**
