### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ALPHAWINS02**
pls accept the pull request

### CODE REVIEW

**Review by ALPHAWINS02 — COMMENTED** [review]
pls review it

**Comment by TheAdityaGupta** [comment]
@ALPHAWINS02 move it to cheatsheets folder

**Comment by ALPHAWINS02** [comment]
> @ALPHAWINS02 move it to the cheatsheets folder
BRO there is no such folder and I think its under web dev only  you need CSS for styling the page 
and if there is such folder pls let me know

**Comment by ALPHAWINS02** [comment]
I DID WHAT U SAID

**Pull request merged**
