### PR TITLE
The School Of Life An Emotional Education

### PR DESCRIPTION
**Pull request by jha-om**

### CODE REVIEW

**Review by TheAdityaGupta — CHANGES_REQUESTED** [review]
Thanks goes, pull req is 
Revert these 2 changes

**Review by TheAdityaGupta — CHANGES_REQUESTED** [review]
Line3 is also correct, revert ur change

**Comment by jha-om** [comment]
> Line3 is also correct, revert ur change

It is, but I have corrected the grammar and little English in it, so that the user can read it properly.

**Comment by TheAdityaGupta** [comment]
the grammar is more wrong with ur changes

**Pull request closed without merging**
